// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mnt_weApi_LaptopManagement_Code_First.Migrations
{
    [DbContext(typeof(mntContext))]
    partial class mntContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mnt_weApi_LaptopManagement_Code_First.Model.Employee", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empId"));

                    b.Property<string>("empname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isLaptopAssigned")
                        .HasColumnType("bit");

                    b.HasKey("empId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("mnt_weApi_LaptopManagement_Code_First.Model.EmployeeLaptopMapping", b =>
                {
                    b.Property<int>("empId")
                        .HasColumnType("int");

                    b.Property<int>("laptopId")
                        .HasColumnType("int");

                    b.Property<bool>("isReturned")
                        .HasColumnType("bit");

                    b.HasKey("empId", "laptopId");

                    b.HasIndex("empId")
                        .IsUnique();

                    b.HasIndex("laptopId")
                        .IsUnique();

                    b.ToTable("EmployeeLaptopMappings");
                });

            modelBuilder.Entity("mnt_weApi_LaptopManagement_Code_First.Model.Laptop", b =>
                {
                    b.Property<int>("laptopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("laptopId"));

                    b.Property<bool>("battery")
                        .HasColumnType("bit");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("charger")
                        .HasColumnType("bit");

                    b.Property<bool>("isAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("keyBoard")
                        .HasColumnType("bit");

                    b.Property<bool>("mic")
                        .HasColumnType("bit");

                    b.Property<string>("modelNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("mouse")
                        .HasColumnType("bit");

                    b.Property<string>("operatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ram")
                        .HasColumnType("int");

                    b.Property<string>("serialNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("speaker")
                        .HasColumnType("bit");

                    b.Property<int>("storage")
                        .HasColumnType("int");

                    b.HasKey("laptopId");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("mnt_weApi_LaptopManagement_Code_First.Model.EmployeeLaptopMapping", b =>
                {
                    b.HasOne("mnt_weApi_LaptopManagement_Code_First.Model.Employee", "Employee")
                        .WithOne("EmployeeLaptopMapping")
                        .HasForeignKey("mnt_weApi_LaptopManagement_Code_First.Model.EmployeeLaptopMapping", "empId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mnt_weApi_LaptopManagement_Code_First.Model.Laptop", "Laptop")
                        .WithOne("EmployeeLaptopMapping")
                        .HasForeignKey("mnt_weApi_LaptopManagement_Code_First.Model.EmployeeLaptopMapping", "laptopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("mnt_weApi_LaptopManagement_Code_First.Model.Employee", b =>
                {
                    b.Navigation("EmployeeLaptopMapping");
                });

            modelBuilder.Entity("mnt_weApi_LaptopManagement_Code_First.Model.Laptop", b =>
                {
                    b.Navigation("EmployeeLaptopMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
